version: '3.9'

services:
  app:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    environment:
      - PORT=${PORT}
      - DB_URI=${DB_URI}
      - EMAIL_USER=${EMAIL_USER}
      - APP_PASSWORD=${APP_PASSWORD}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules